name: Build, Test, and Deploy LaTeX PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: texlive-${{ runner.os }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Install minimal TeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode ResumeAAE.tex
          pdflatex -interaction=nonstopmode ResumeAAE.tex

      - name: Test if PDF was generated
        run: |
          if [ ! -f ResumeAAE.pdf ]; then
            echo "❌ PDF not generated. Failing build."
            exit 1
          else
            echo "✅ PDF generated successfully."
          fi

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install minimal TeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode ResumeAAE.tex
          pdflatex -interaction=nonstopmode ResumeAAE.tex

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          exclude_assets: '**/*.tex'
